import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased absolute top-0 z-40 w-screen h-screen`}
      >
        <section className="w-screen h-screen overflow-hidden relative">
          <NavBar />
          <div className="flex flex-row h-[calc(100vh-50px)] border-r-width-0.4 border-b-Neutrals-200 bg-slate-400">
            {children}
          </div>
        </section>
      </body>
    </html>
  );
}
